### ISSUE TITLE
TypeError: Key must be a buffer

### ISSUE THREAD

**Issue by crapthings** [lazorfuzz/signalbuddy#2]
```

TypeError: Key must be a buffer
    at new Hmac (crypto.js:117:16)
    at Object.createHmac (crypto.js:643:10)
    at /home/cube/signalbuddy/dist/sockets.js:153:37
    at Array.forEach (<anonymous>)
    at Namespace.<anonymous> (/home/cube/signalbuddy/dist/sockets.js:152:26)
    at emitOne (events.js:116:13)
    at Namespace.emit (events.js:211:7)
    at Namespace.emit (/home/cube/signalbuddy/node_modules/socket.io/lib/namespace.js:209:10)
    at /home/cube/signalbuddy/node_modules/socket.io/lib/namespace.js:177:14
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
```

clone
build
start

node - v8.9.4

**Comment by crapthings** [comment]
what is a turn server secret ???

i use coturn as turn server

from document there's only --use-auth-secret

is this the same thing to use auth secret?

**Comment by crapthings** [comment]
after searching it looks like 

https://stackoverflow.com/questions/35766382/coturn-how-to-use-turn-rest-api

**Comment by crapthings** [comment]
works after upgrade to node v10.x
